import bcrypt from 'bcryptjs';

const data = {
  users: [
    {
      name: 'John',
      email: 'John@example.com',
      password: bcrypt.hashSync('123456'),
      isAdmin: true,
      userID: '1',
      isSeller: true,
      account_number: '123456789'

    },
    {
      name: 'Jacob',
      email: 'Jacob@example.com',
      password: bcrypt.hashSync('123456'),
      isAdmin: true,
      userID: '2',
      isSeller: false,
      account_number: '234567891'

    },
    {
      name: 'Jane',
      email: 'Jane@example.com',
      password: bcrypt.hashSync('123456'),
      isAdmin: false,
      userID: '3',
      isSeller: false,
      account_number: '345678912'

    },
  ],
  banking: [
    {
      name: 'John',
      email: 'John@example.com',
      account_number: '123456789',
      credit_card_number: '1234',
      cvv: '123',
      exp: '12/21',
      balance: 5000

    },
    {
      name: 'Jacob',
      email: 'Jacob@example.com',
      account_number: '234567891',
      credit_card_number: '2345',
      cvv: '234',
      exp: '12/21',
      balance: 5000
    },
    {
      name: 'Jane',
      email: 'Jane@example.com',
      account_number: '345678912',
      credit_card_number: '3456',
      cvv: '345',
      exp: '12/21',
      balance: 5000

    },
    {
      name: 'Infitity Store',
      email: 'Infinity@example.com',
      account_number: '000000000',
      credit_card_number: '0000',
      cvv: '000',
      exp: '12/21',
      balance: 5000

    },
  ],
  products: [
    {
      name: 'Free Shirt',
      slug: 'free-shirt',
      category: 'Shirts',
      image: 'https://th.bing.com/th/id/OIP.8_5dV0jFar_UjUmKIGiJwQHaJg?pid=ImgDet&rs=1',
      price: 70,
      brand: 'Nike',
      rating: 4.5,
      numReviews: 8,
      countInStock: 20,
      description: 'A popular shirt',
      isFeatured: true,
      email: 'John@example.com',
      id: '1',
      coupon: '1234',
      discount: 0.2,
      iscoupon: true,
    },
    {
      name: 'Fit Shirt',
      slug: 'fit-shirt',
      category: 'Shirts',
      image: 'https://th.bing.com/th/id/OIP.JmSw7gPGFExtQLCvooFnTQHaJT?pid=ImgDet&rs=1',
      price: 80,
      brand: 'Adidas',
      rating: 3.2,
      numReviews: 10,
      countInStock: 20,
      description: 'A popular shirt',
      isFeatured: true,
      email: 'John@example.com',
      id: '2',
      coupon: '1234',
      discount: 0.2,
      iscoupon: true,
    },
    {
      name: 'Slim Shirt',
      slug: 'slim-shirt',
      category: 'Shirts',
      image: 'https://th.bing.com/th/id/OIP.n_1e_2WrwGgmrMjmybESiwHaIq?pid=ImgDet&rs=1',
      price: 90,
      brand: 'Raymond',
      rating: 4.5,
      numReviews: 3,
      countInStock: 20,
      description: 'A popular shirt',
      isFeatured: true,
      email: 'John@example.com',
      id: '3',
      coupon: '1234',
      discount: 0.2,
      iscoupon: true,
    },
    {
      name: 'Golf Pants',
      slug: 'golf-pants',
      category: 'Pants',
      image: 'https://th.bing.com/th/id/OIP.aBaFR9cYVVTZiwk_N1zScAHaHa?pid=ImgDet&rs=1',
      price: 90,
      brand: 'Oliver',
      rating: 2.9,
      numReviews: 13,
      countInStock: 20,
      description: 'Smart looking pants',
      isFeatured: true,
      email: 'John@example.com',
      id: '4',
      coupon: '1234',
      discount: 0.2,
      iscoupon: true,
    },
    {
      name: 'Fit Pants',
      slug: 'fit-pants',
      category: 'Pants',
      image: 'https://th.bing.com/th/id/OIP.7nM3X1DzCO4KaImQ4o0PYAHaLH?pid=ImgDet&rs=1',
      price: 95,
      brand: 'Zara',
      rating: 3.5,
      numReviews: 7,
      countInStock: 20,
      description: 'A popular pants',
      isFeatured: true,
      email: 'John@example.com',
      id: '5',
      coupon: '1234',
      discount: 0.2,
      iscoupon: true,
    },
    {
      name: 'Classic Pants',
      slug: 'classic-pants',
      category: 'Pants',
      image: 'https://th.bing.com/th/id/OIP.9cz0R85Y_JwcAKFz4JW9LwHaJQ?pid=ImgDet&rs=1',
      price: 75,
      brand: 'Casely',
      rating: 2.4,
      numReviews: 14,
      countInStock: 20,
      description: 'A popular pants',
      isFeatured: true,
      email: 'John@example.com',
      id: '6',
      coupon: '1234',
      discount: 0.2,
      iscoupon: true,
    },
  ],
};

export default data;